apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../cert-manager
  - ../../../../cloudflared
  - ../../../../metrics-server
  - ../../../../traefik
  - ../../../../vertical-pod-autoscaler
  - ../../../../homepage
